package paq_sumillas.ejb;


import javax.ejb.Stateless;


/**
 * @author 
 *
 */
@Stateless
public class ServicioDestinatario {		
	
	public String getEmpleadoContrato(String estado){
		String sql_empleadoContrato="SELECT EMP.APELLIDO_PATERNO_GTEMP || ' ' || (case when EMP.APELLIDO_MATERNO_GTEMP is null then '' else EMP.APELLIDO_MATERNO_GTEMP end)  || ' ' ||EMP.PRIMER_NOMBRE_GTEMP || ' ' || (case when EMP.SEGUNDO_NOMBRE_GTEMP is null then '' else EMP.SEGUNDO_NOMBRE_GTEMP end) " +
				" AS NOMBRES_APELLIDOS, " +
				"EMP.APELLIDO_PATERNO_GTEMP || ' ' || (case when EMP.APELLIDO_MATERNO_GTEMP is null then '' else EMP.APELLIDO_MATERNO_GTEMP end)  || ' ' ||EMP.PRIMER_NOMBRE_GTEMP || ' ' || (case when EMP.SEGUNDO_NOMBRE_GTEMP is null then '' else EMP.SEGUNDO_NOMBRE_GTEMP end) " +
				" AS NOMBRES_APELLIDOS, DEPA.DETALLE_GEDEP FROM GEN_EMPLEADOS_DEPARTAMENTO_PAR EPAR " +
				" LEFT JOIN GTH_EMPLEADO EMP ON EMP.IDE_GTEMP=EPAR.IDE_GTEMP LEFT JOIN SIS_SUCURSAL SUCU ON SUCU.IDE_SUCU=EPAR.IDE_SUCU " +
				" LEFT JOIN GEN_DEPARTAMENTO DEPA ON DEPA.IDE_GEDEP=EPAR.IDE_GEDEP LEFT JOIN GEN_AREA AREA ON AREA.IDE_GEARE=EPAR.IDE_GEARE " +
				" WHERE EPAR.ACTIVO_GEEDP in ("+estado+")";
		return sql_empleadoContrato;
	}
	
	public String getEmpleadoContratoCargo(String nombresApellidos){
		String sql_empleadoContrato="select DETALLE_GECAF from GEN_CARGO_FUNCIONAL WHERE"+ 
				" PRINCIPAL_SECUNDARIO_GECAF=TRUE AND GEN_CARGO_FUNCIONAL.IDE_GECAF = ("+
				"SELECT IDE_GECAF FROM GEN_EMPLEADOS_DEPARTAMENTO_PAR "+
				"WHERE GEN_EMPLEADOS_DEPARTAMENTO_PAR.IDE_GEDED =(SELECT a.IDE_GEDED FROM GEN_DETALLE_EMPLEADO_DEPARTAME a LEFT JOIN ( SELECT IDE_GEINS,DETALLE_GEINS FROM GEN_INSTITUCION)b ON a.IDE_GEINS=b.IDE_GEINS LEFT JOIN ("+ 
				"SELECT a.IDE_GEAME AS IDE_GEAME,b.DETALLE_GEAED,c.DETALLE_GEMED FROM GEN_ACCION_MOTIVO_EMPLEADO a LEFT JOIN(SELECT IDE_GEAED,DETALLE_GEAED from GEN_ACCION_EMPLEADO_DEPA )b"+ 
				" ON b.IDE_GEAED=a.IDE_GEAED LEFT JOIN ( SELECT IDE_GEMED,DETALLE_GEMED FROM GEN_MOTIVO_EMPLEADO_DEPA )c ON c.IDE_GEMED=a.IDE_GEMED ORDER BY  b.DETALLE_GEAED,"+
				" c.DETALLE_GEMED )c ON c.IDE_GEAME=a.IDE_GEAME WHERE a.IDE_GTEMP=(SELECT IDE_GTEMP FROM GTH_EMPLEADO EMP WHERE (EMP.APELLIDO_PATERNO_GTEMP || ' ' || (case when EMP.APELLIDO_MATERNO_GTEMP is null then '' else EMP.APELLIDO_MATERNO_GTEMP end)  || ' ' ||EMP.PRIMER_NOMBRE_GTEMP || ' ' || (case when EMP.SEGUNDO_NOMBRE_GTEMP is null then '' else EMP.SEGUNDO_NOMBRE_GTEMP end))='"+nombresApellidos+"') ORDER BY IDE_GEDED DESC LIMIT 1) AND IDE_GTEMP=((SELECT IDE_GTEMP FROM GTH_EMPLEADO EMP WHERE (EMP.APELLIDO_PATERNO_GTEMP || ' ' || (case when EMP.APELLIDO_MATERNO_GTEMP is null then '' else EMP.APELLIDO_MATERNO_GTEMP end)  || ' ' ||EMP.PRIMER_NOMBRE_GTEMP || ' ' || (case when EMP.SEGUNDO_NOMBRE_GTEMP is null then '' else EMP.SEGUNDO_NOMBRE_GTEMP end))='"+nombresApellidos+"') ORDER BY IDE_GEDED DESC LIMIT 1)"+
				")";
		return sql_empleadoContrato;
	}
	
}
